#loc = loc(unknown)
#loc1 = loc("Const:")
#loc2 = loc("Const")
#loc3 = loc("Placeholder:")
#loc4 = loc("Placeholder")
#loc5 = loc("Mul:")
#loc6 = loc("Mul")
#loc7 = loc("Identity:")
#loc8 = loc("Output_1")
module attributes {tf.versions = {bad_consumers = [], min_consumer = 0 : i32, producer = 716 : i32}} {
  func.func @main() -> tensor<?x8x1024xf32> attributes {tf.entry_function = {control_outputs = "", inputs = "", outputs = "Output_1:0"}} {
    %0 = tf_executor.graph {
      %outputs, %control = tf_executor.island wraps "tf.Const"() {_symbolic_output_shapes = [#tf_type.shape<>], device = "", value = dense<5.000000e-01> : tensor<f32>} : () -> tensor<f32> loc(#loc9)
      %outputs_0, %control_1 = tf_executor.island wraps "tf.Placeholder"() {_symbolic_output_shapes = [#tf_type.shape<137x8x1024>], device = "", shape = #tf_type.shape<?x8x1024>} : () -> tensor<?x8x1024xf32> loc(#loc10)
      %outputs_2, %control_3 = tf_executor.island wraps "tf.Mul"(%outputs, %outputs_0) {_symbolic_output_shapes = [#tf_type.shape<137x8x1024>], device = ""} : (tensor<f32>, tensor<?x8x1024xf32>) -> tensor<?x8x1024xf32> loc(#loc11)
      %outputs_4, %control_5 = tf_executor.island wraps "tf.Identity"(%outputs_2) {_symbolic_output_shapes = [#tf_type.shape<137x8x1024>], device = ""} : (tensor<?x8x1024xf32>) -> tensor<?x8x1024xf32> loc(#loc12)
      tf_executor.fetch %outputs_4 : tensor<?x8x1024xf32> loc(#loc)
    } loc(#loc)
    return %0 : tensor<?x8x1024xf32> loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc9 = loc(fused["Const:", "Const"])
#loc10 = loc(fused["Placeholder:", "Placeholder"])
#loc11 = loc(fused["Mul:", "Mul"])
#loc12 = loc(fused["Identity:", "Output_1"])
