x1: test1.cpp
	clang++ -Xclang -ast-print -fsyntax-only test1.cpp > test1.cppx

x2: test2.cpp
	clang++ -Xclang -ast-print -fsyntax-only test2.cpp > test2.cppx

x3: test3.cpp
	clang++ -Xclang -ast-print -fsyntax-only test3.cpp > test3.cppx

x4: test4.cpp
	clang++ -Xclang -ast-print -fsyntax-only test4.cpp > test4.cppx

t2: test2.cpp
	clang++ -o test2 test2.cpp